site: Leqa's blog
url: https://leqa.xyz
title: Leqa's blog
description: Đơn giản chỉ là ghi và chép.
permalink: pretty

paginate: 1000
paginate_path: "/page:num/"

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style:    :compressed

plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      
  - scope:
      path: "assets/images"
    values:
      image: true

comment-post: https://docs.google.com/forms/d/e/1FAIpQLSd8kuq8XPRmrHv2uIsM-X8qPR0jWriAhslXs3QweM40tLxU_A/viewform?usp=sf_link
comment-read: https://docs.google.com/spreadsheets/d/1yeBdrkYcDw2hvTpGavtKHvew-81sLZQFXDYr9156J94/edit?usp=sharing
