site: Cáo ăn chay
url: https://caoanchay.github.io
title: Cáo ăn chay
description: Đơn giản chỉ là ghi và chép.

permalink: pretty

paginate:            10
paginate_path:       "/page:num/"
baseurl:             ""

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir:          _sass
  style:            :compressed

plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  projects:
    output: true
    permalink: /projects/:slug

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      
  - scope:
      path: "assets/images"
    values:
      image: true
